### ISSUE TITLE
Ask ! 

### ISSUE THREAD

**Issue by OnlyFaris** [fedes1to/Zygisk-ImGui-Menu#1]
Why it doesn't work in 32bit lib? 🤔

**Comment by fedes1to** [comment]
because it didnt have the necessary libraries, i updated it though, you can test it now

**Comment by OnlyFaris** [comment]
> because it didnt have the necessary libraries, i updated it though, you can test it now

okey thanks I will try it :3

**Comment by OnlyFaris** [comment]
> because it didnt have the necessary libraries, i updated it though, you can test it now

Still not working for 32bit

**Comment by fedes1to** [comment]
> > because it didnt have the necessary libraries, i updated it though, you can test it now
> 
> Still not working for 32bit

make sure you have put the correct arch inside the build.gradle (ndk.abiFilters) and that you select the build variant as the 32-bit one.
