### ISSUE TITLE
The application won't open

### ISSUE THREAD

**Issue by Dapz123** [fedes1to/Zygisk-ImGui-Menu#14]
For the first time there is nothing wrong, I injected imgui and it worked normally. 
But when I write this hook: 
Function.cpp:
```
int DashSpeed = 1;

float (*old_getDashSpeed)(void *instance);
float getDashSpeed(void *instance) {
    if (instance != NULL && DashSpeed > 1) {
        return (float) DashSpeed;
    }
    return old_getDashSpeed(instance);
}

void Hooks() {
   HOOK("0x405db88", old_getDashSpeed, getDashSpeed);
}
```

When I injected, the game wouldn't open. It was forced to close. Is the hook I wrote wrong?

**Comment by fedes1to** [comment]
EMULATORS ARE NOT SUPPORTED !!!!!!
