### ISSUE TITLE
x86_64 cant control imgur 

### ISSUE THREAD

**Issue by liusj5257** [fedes1to/Zygisk-ImGui-Menu#2]
I have merged the latest injection method version of Zygisk-Il2CppDumper into this repository. It has been tested on a mobile phone and can successfully draw imgur and control it. However, when tested on a x86_64 emulator on a computer, it can successfully draw imgur but cannot control it.

**Comment by fedes1to** [comment]
you have to hook egl and check input positions, you dont need to merge any injection method btw, it should work as is, also emulators arent supported

**Comment by Yokimt** [comment]
I encountered the same issue. How did you resolve it?

**Comment by Yokimt** [comment]
The hook is effective, but the menu cannot be controlled.
