### ISSUE TITLE
Add render vulkan

### ISSUE THREAD

**Issue by QPLAYid** [fedes1to/Zygisk-ImGui-Menu#20]
Please add render vulkan

**Comment by fedes1to** [comment]
that would require major changes, just fork it yourself and change the eglswapbuffers draw

**Comment by QPLAYid** [comment]
> that would require major changes, just fork it yourself and change the eglswapbuffers draw

how ? can you add on you project ?

**Comment by fedes1to** [comment]
no, requires too much work and i dont have time, if you ever get it working feel free to do a pull request
