### ISSUE TITLE
Touch issue on smaller screen but working perfectly on bigger screen 

### ISSUE THREAD

**Issue by Ahmad4zmi** [fedes1to/Zygisk-ImGui-Menu#26]
When i use mod menu on my Xiaomi Pad 6 it work perfectly and when i use it on my Redmi note 9 pro I need to click above the checkbox like if I click on first checkbox the second checkbox will get clicked and when i clicked on second then third one get clicked pls help

**Comment by fedes1to** [comment]
set glWidth and glHeight according to the resolution set by the game instead of using the egl calls

see: https://docs.unity3d.com/6000.0/Documentation/ScriptReference/Screen-resolutions.html
