### ISSUE TITLE
how to make libanogs work

### ISSUE THREAD

**Issue by nvtx001** [fedes1to/Zygisk-ImGui-Menu#4]

**Comment by fedes1to** [comment]
what the heck is a libanogs

**Comment by nvtx001** [comment]
libanogs.so

> Cái quái gì là một libanogs

**Comment by fedes1to** [comment]
just change libil2cpp.so to that

**Comment by nvtx001** [comment]
But I Want Use Two Lib Libil2cpp.so And Libanogs.so

Vào 0:57, Th 6, 2 thg 6, 2023 fedesito ***@***.***> đã viết:

**Comment by fedes1to** [comment]
oh then make a basemap for kittymemory and make sure you specify in the macro which library needs to be hooked for dobby

**Comment by chrisc06** [comment]
this template is only made for unity games.

**Comment by fedes1to** [comment]
ok now that ive modded tencent games ik what libanogs is, its present on unity games aswell, to access the library do the same whats done on libil2cpp.so as i said before

**Comment by nvtx001** [comment]
> ok now that ive modded tencent games ik what libanogs is, its present on unity games aswell, to access the library do the same whats done on libil2cpp.so as i said before

Can You Help Me Modify Misc.h. Sorry Because I'm not good at coding 🥲
