### ISSUE TITLE
ImGui doesn't render, and the game crashes upon screen touch

### ISSUE THREAD

**Issue by 0x256e4** [fedes1to/Zygisk-ImGui-Menu#8]
Game : Blue Archive
Lib : il2cpp.so

how to fix this issue?

**Comment by fedes1to** [comment]
maybe the input symbol isnt found, you can try finding the "nativeInjectEvent" pointer using kittymemory's nativelib scanner to enable proper touch.

for the rendering part, make sure that the game uses egl (opengl 2.x/3.x) if not you'll need to find a different render buffer method to hook to.
