### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Irhtn** [fedes1to/Zygisk-ImGui-Menu#9]
I found a game does not call "eglSwapBuffers",and it caused some crash.What should I do to find the right function

**Comment by Irhtn** [comment]
Could you give me some clues on how to find a new render buffer method?

**Comment by ghost** [comment]
That is because some games using Vulkan render instead OpenGLES

**Comment by fedes1to** [comment]
Try to find the swap buffers for vulkan and hook that instead
